<?php

namespace Database\Seeders;

use App\Models\PartnerEnvironment;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PartnerEnvironmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table(PartnerEnvironment::TABLE_NAME)->insertTs(
            [
                [
                    'partner_id' => 1,
                    'environment_id' => 2,
                    'status' => 1,
                    'check_redeem_url' => 'http://syst-gcapi.godream.com/v1/SimpleCanRedeem?format=json',
                    'redeem_url' => 'http://syst-gcapi.godream.com/v1/SimpleRedeem?format=json',
                    'url' => null,
                    'username' => null,
                    'password' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'partner_inc' => null,
                    'partner_code' => null,
                    'user_id' => null,
                    'c_user_id' => null,
                ],
                [
                    'partner_id' => 2,
                    'environment_id' => 2,
                    'status' => 1,
                    'partner_inc' => 'Hotel Express International',
                    'partner_code' => 'F3641',
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                    'url' => 'https://external-oasismws.wonderbox.com/oasis/redemption/redeem',
                    'username' => null,
                    'password' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'user_id' => null,
                    'c_user_id' => null,
                ],
                [
                    'partner_id' => 2,
                    'environment_id' => 1,
                    'status' => 0,
                    'partner_inc' => 'Hotel Express International',
                    'partner_code' => 'F3641',
                    'url' => 'https://preprod-external-oasismws.wonderbox.com/oasis/redemption/redeem',
                    'username' => null,
                    'password' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'user_id' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 3,
                    'environment_id' => 2,
                    'status' => 1,
                    'url' => 'https://www.tinggly.com/api/hotelexpress',
                    'password' => 'q9nUKUGcmmLRtBi',
                    'user_id' => 'hotelexpressapi@tinggly.com',
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 3,
                    'environment_id' => 1,
                    'status' => 0,
                    'url' => 'https://beta.tinggly.com/api/hotelexpress',
                    'password' => 'q9nUKUGcmmLRtBi',
                    'user_id' => 'hotelexpressapi@tinggly.com',
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 5,
                    'environment_id' => 2,
                    'status' => 1,
                    'url' => 'https://giftingowl.com/API/suppliers/hei/book',
                    'api_key' => 'NX:S:K:0bc8cdfb7882371d259f1945bb7d3572148beec355e463d09dcd2657557cc054d6d77cafe56c2c97c56091f2d85342b4cd046eeb20f3d8623394b000392f173f',
                    'type' => 'hei',
                    'user_id' => '2d1a5059-94b2-9e25-d42b-58c42efd79c4',
                    'c_user_id' => '5edd3c27-3b65-247e-8961-8fec3ddbc9ca',
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                    'password' => null
                ],
                [
                    'partner_id' => 5,
                    'environment_id' => 1,
                    'status' => 0,
                    'url' => 'https://dev.giftingowl.com/API/suppliers/hei/book',
                    'api_key' => 'NX:S:K:ed23d8f7cd890c2f9ea95ce045e96757a093c1d826cd3539bee5ff843bb9069ef95f1f9cd8bb8f41c0e140eb7dfc2516cfac59da1c2288bc6a9b65a4e569c388',
                    'type' => 'hei',
                    'user_id' => 'e38e3c02-2e83-bed6-ae2f-430dea99d010',
                    'c_user_id' => '2ca3bcfb-ed49-b3bc-8eed-677334874fea',
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                    'password' => null
                ],
                [
                    'partner_id' => 6,
                    'environment_id' => 2,
                    'status' => 1,
                    'url' => 'https://www.laisvalaikiodovanos.lt/api/hotelexpress',
                    'password' => '9PKuqW22Rkg5pxLe',
                    'user_id' => 'otelexpressapi@laisvalaikiodovanos.lt',
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 6,
                    'environment_id' => 1,
                    'status' => 0,
                    'url' => 'http://beta.laisvalaikiodovanos.lt/api/hotelexpress',
                    'password' => '9PKuqW22Rkg5pxLe',
                    'user_id' => 'otelexpressapi@laisvalaikiodovanos.lt',
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 7,
                    'environment_id' => 2,
                    'status' => 1,
                    'url' => 'https://www.wyjatkowyprezent.pl/api/hotelexpress',
                    'password' => '9PKuqW22Rkg5pxLe',
                    'user_id' => 'hotelexpressapi@laisvalaikiodovanos.lt',
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 7,
                    'environment_id' => 1,
                    'status' => 0,
                    'url' => 'http://beta.wyjatkowyprezent.pl/api/hotelexpress',
                    'password' => '9PKuqW22Rkg5pxLe',
                    'user_id' => 'hotelexpressapi@laisvalaikiodovanos.lt',
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 8,
                    'environment_id' => 2,
                    'status' => 1,
                    'url' => 'https://www.davanuserviss.lv/api/hotelexpress',
                    'password' => '9PKuqW22Rkg5pxLe',
                    'user_id' => 'hotelexpressapi@laisvalaikiodovanos.lt',
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 8,
                    'environment_id' => 1,
                    'status' => 0,
                    'url' => 'http://beta.davanuserviss.lv/api/hotelexpress',
                    'password' => '9PKuqW22Rkg5pxLe',
                    'user_id' => 'hotelexpressapi@laisvalaikiodovanos.lt',
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 9,
                    'environment_id' => 2,
                    'status' => 1,
                    'url' => 'https://www.kingitus.ee/api/hotelexpress',
                    'password' => '9PKuqW22Rkg5pxLe',
                    'user_id' => 'hotelexpressapi@laisvalaikiodovanos.lt',
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 9,
                    'environment_id' => 1,
                    'status' => 0,
                    'url' => 'http://beta.kingitus.ee/api/hotelexpress',
                    'password' => '9PKuqW22Rkg5pxLe',
                    'user_id' => 'hotelexpressapi@laisvalaikiodovanos.lt',
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 10,
                    'environment_id' => 2,
                    'status' => 1,
                    'url' => 'https://r02-external-oasismws.wonderbox.com/oasis/redemption/redeem',
                    'partner_inc' => 'Hotel Express International',
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'user_id' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                    'password' => null
                ],
                [
                    'partner_id' => 11,
                    'environment_id' => 2,
                    'status' => 1,
                    'url' => 'https://cpfilemaker.com/webapi',
                    'password' => '9PKuqW22Rkg5pxLe',
                    'api_key' => 'api_hei',
                    'api_token' => '1AFE6577A45337F75D0ED90A1A654BACC1C7D51FB474C496AC43783DB3BB94C7819A34EA00BF41A9F1F65ED392551C30D9DAD98227E155C717BF3363074D0DD44E',
                    'host' => '127.0.0.1',
                    'port' => 'cpfilemaker.com:11001',
                    'protocol' => 'http',
                    'database' => 'Coffrets_Prestige',
                    'layout_check' => 'API_HEI_Check',
                    'layout_redeem' => 'API_HEI_Redeem',
                    'action' => 'FindRecords',
                    'get_balance_script' => 'API_Givex_GetBalance_hei',
                    'get_redeem_script' => 'API_Givex_GetRedeem_hei',
                    'type' => 'find',
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'user_id' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
            ]
        );
    }
}
