<?php

namespace Database\Seeders;

use App\Models\PartnerEnvironment;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PartnerEnvironmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table(PartnerEnvironment::TABLE_NAME)->insertTs(
            [
                [
                    'partner_id' => 1,
                    'environment_id' => 2,
                    'status' => 1,
                    'check_redeem_url' => 'http://example.com/',
                    'redeem_url' => 'http://example.com/',
                    'url' => null,
                    'username' => null,
                    'password' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'partner_inc' => null,
                    'partner_code' => null,
                    'user_id' => null,
                    'c_user_id' => null,
                ],
                [
                    'partner_id' => 2,
                    'environment_id' => 2,
                    'status' => 1,
                    'partner_inc' => null,
                    'partner_code' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                    'url' => 'http://example.com/',
                    'username' => null,
                    'password' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'user_id' => null,
                    'c_user_id' => null,
                ],
                [
                    'partner_id' => 2,
                    'environment_id' => 1,
                    'status' => 0,
                    'partner_inc' => null,
                    'partner_code' => null,
                    'url' => 'http://example.com/',
                    'username' => null,
                    'password' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'user_id' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 3,
                    'environment_id' => 2,
                    'status' => 1,
                    'url' => 'http://example.com/',
                    'password' => null,
                    'user_id' => null,
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 3,
                    'environment_id' => 1,
                    'status' => 0,
                    'url' => 'http://example.com/',
                    'password' => null,
                    'user_id' => null,
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 5,
                    'environment_id' => 2,
                    'status' => 1,
                    'url' => 'http://example.com/',
                    'api_key' => null,
                    'type' => 'hotel',
                    'user_id' => null,
                    'c_user_id' => null,
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                    'password' => null
                ],
                [
                    'partner_id' => 5,
                    'environment_id' => 1,
                    'status' => 0,
                    'url' => 'http://example.com/',
                    'api_key' => null,
                    'type' => 'hotel',
                    'user_id' => null,
                    'c_user_id' => null,
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                    'password' => null
                ],
                [
                    'partner_id' => 6,
                    'environment_id' => 2,
                    'status' => 1,
                    'url' => 'http://example.com/',
                    'password' => null,
                    'user_id' => null,
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 6,
                    'environment_id' => 1,
                    'status' => 0,
                    'url' => 'http://example.com/',
                    'password' => null,
                    'user_id' => null,
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 7,
                    'environment_id' => 2,
                    'status' => 1,
                    'url' => 'http://example.com/',
                    'password' => null,
                    'user_id' => null,
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 7,
                    'environment_id' => 1,
                    'status' => 0,
                    'url' => 'http://example.com/',
                    'password' => null,
                    'user_id' => null,
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 8,
                    'environment_id' => 2,
                    'status' => 1,
                    'url' => 'http://example.com/',
                    'password' => null,
                    'user_id' => null,
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 8,
                    'environment_id' => 1,
                    'status' => 0,
                    'url' => 'http://example.com/',
                    'password' => null,
                    'user_id' => null,
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 9,
                    'environment_id' => 2,
                    'status' => 1,
                    'url' => 'http://example.com/',
                    'password' => null,
                    'user_id' => null,
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 9,
                    'environment_id' => 1,
                    'status' => 0,
                    'url' => 'http://example.com/',
                    'password' => null,
                    'user_id' => null,
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
                [
                    'partner_id' => 10,
                    'environment_id' => 2,
                    'status' => 1,
                    'url' => 'http://example.com/',
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'api_key' => null,
                    'api_token' => null,
                    'host' => null,
                    'port' => null,
                    'protocol' => null,
                    'database' => null,
                    'layout_check' => null,
                    'layout_redeem' => null,
                    'action' => null,
                    'get_balance_script' => null,
                    'get_redeem_script' => null,
                    'type' => null,
                    'user_id' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                    'password' => null
                ],
                [
                    'partner_id' => 11,
                    'environment_id' => 2,
                    'status' => 1,
                    'url' => 'http://example.com/',
                    'password' => null,
                    'api_key' =>  null,
                    'api_token' => null,
                    'host' => '127.0.0.1',
                    'port' => '80',
                    'protocol' => 'http',
                    'database' => 'db_name',
                    'layout_check' => 'api_check',
                    'layout_redeem' => 'api_redeem',
                    'action' => 'find',
                    'get_balance_script' => 'api_get_balance',
                    'get_redeem_script' => 'api_get_redeem',
                    'type' => 'find',
                    'partner_inc' => null,
                    'partner_code' => null,
                    'username' => null,
                    'user_id' => null,
                    'c_user_id' => null,
                    'redeem_url' => null,
                    'check_redeem_url' => null,
                ],
            ]
        );
    }
}
